// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"net/http"
	"sync"
)

// HttpClientMock is a mock implementation of main.HttpClient.
//
//	func TestSomethingThatUsesHttpClient(t *testing.T) {
//
//		// make and configure a mocked main.HttpClient
//		mockedHttpClient := &HttpClientMock{
//			DoFunc: func(req *http.Request) (*http.Response, error) {
//				panic("mock out the Do method")
//			},
//		}
//
//		// use mockedHttpClient in code that requires main.HttpClient
//		// and then make assertions.
//
//	}
type HttpClientMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(req *http.Request) (*http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Req is the req argument value.
			Req *http.Request
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *HttpClientMock) Do(req *http.Request) (*http.Response, error) {
	if mock.DoFunc == nil {
		panic("HttpClientMock.DoFunc: method is nil but HttpClient.Do was just called")
	}
	callInfo := struct {
		Req *http.Request
	}{
		Req: req,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(req)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedHttpClient.DoCalls())
func (mock *HttpClientMock) DoCalls() []struct {
	Req *http.Request
} {
	var calls []struct {
		Req *http.Request
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}

// ResetDoCalls reset all the calls that were made to Do.
func (mock *HttpClientMock) ResetDoCalls() {
	mock.lockDo.Lock()
	mock.calls.Do = nil
	mock.lockDo.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *HttpClientMock) ResetCalls() {
	mock.lockDo.Lock()
	mock.calls.Do = nil
	mock.lockDo.Unlock()
}
